config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True


postgres:
  outputs:
    dev:
      type: postgres
      threads: 3
      host: localhost
      port: 5432
      user: shpz
      pass: "12345"
      dbname: tmp
      schema: stg
  target: dev